Feature toevoegen klant
DaaromThomas/FrontendVdLelie_Angular pull request #27
Opened 2023-12-20 13:29 UTC by ronp2001

A simple overview of current existing customers, and a pop-up to add new ones

2023-12-21 08:42 UTC, davidvdw02 requested changes

2023-12-21 08:42 UTC, davidvdw02 commented on src/app/customers/add-customer-popup/add-customer-popup.component.ts
> +  constructor(private storageService: DataStorageService, private renderer: Renderer2) {}
renderer2?

2023-12-21 08:42 UTC, davidvdw02 commented on src/app/customers/add-customer-popup/add-customer-popup.component.ts
> +    this.mutationObserver = new MutationObserver((mutations) => {
geen andere manier?

2023-12-21 08:42 UTC, davidvdw02 commented on src/app/customers/add-customer-popup/add-customer-popup.component.ts
> +  }
use form validators

2023-12-21 08:42 UTC, davidvdw02 commented on src/app/services/data-storage.service.ts
> +    if (newCustomer.phonenumber !== null) {
checks zijn toch al gedaan? in de form shizzle

2023-12-21 08:42 UTC, davidvdw02 commented on src/app/services/data-storage.service.ts
> +  storeCustomer(newCustomer: Customer) {
test?

2023-12-21 08:42 UTC, ronp2001 commented on src/app/customers/add-customer-popup/add-customer-popup.component.ts
> +  constructor(private storageService: DataStorageService, private renderer: Renderer2) {}
@DaaromThomas

2023-12-21 08:42 UTC, ronp2001 commented on src/app/customers/add-customer-popup/add-customer-popup.component.ts
> +    this.mutationObserver = new MutationObserver((mutations) => {
@DaaromThomas

2023-12-21 12:08 UTC, ronp2001 commented on src/app/customers/add-customer-popup/add-customer-popup.component.ts
> +  }
form validators are also not being used in addProductPopup, i wouldn't mind changing this at some point but for now i think this will be a decent enough solution

2023-12-21 12:11 UTC, ronp2001 commented on src/app/services/data-storage.service.ts
> +    if (newCustomer.phonenumber !== null) {
email check can be removed other then that, if i do not do this check the value "null" gets stored in the database, so either logic on the back-end isn't working as expected

2023-12-21 12:31 UTC, davidvdw02 commented on src/app/customers/add-customer-popup/add-customer-popup.component.ts
> +  }
grr

2023-12-21 12:32 UTC, davidvdw02 commented on src/app/services/data-storage.service.ts
> +    if (newCustomer.phonenumber !== null) {
prima jonge

2023-12-21 12:40 UTC, ronp2001 commented on src/app/customers/add-customer-popup/add-customer-popup.component.ts
> +    this.mutationObserver = new MutationObserver((mutations) => {
as requested (irl) currently working on a test for this function

2023-12-21 21:25 UTC, ronp2001 commented on src/app/customers/add-customer-popup/add-customer-popup.component.ts
> +    this.mutationObserver = new MutationObserver((mutations) => {
see:
https://github.com/DaaromThomas/FrontendVdLelie_Angular/pull/27/commits/16329f869813d5f725618117f2e4634f945ce9aa

2023-12-22 08:37 UTC, davidvdw02 approved these changes

2023-12-22 08:37 UTC, merged